## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = true
#canonifyURLs = "true"

# Local

publishDir = "public"

# Remote
baseURL = "https://doanxuanbach.github.io/hugo-portfolio-source/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------
disableKinds = ["taxonomy", "section", "RSS"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
[menu]
  [[menu.main]]
    name = "About"
    url = "/posts/about/"
    weight = 10

  [[menu.main]]
    name = "Projects"
    url = "/posts/projects/"
    weight = 20
  [[menu.main]]
    name = "Http-lab"
    url = "/posts/http-lab/"
    weight = 30
  [[menu.main]]
     name = "Webpack Docker"
     url = "/posts/webpack-docker/"
     weight = 40
  [[menu.main]]
     name = "Bootstrap Luxon"
     url = "/posts/bootstrap-luxon/"
     weight = 50